name: AWS
on:
  push:
    branches: [dev]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn --immutable

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build Application
        run: yarn build

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - if: github.ref == 'refs/heads/dev'
        name: Create Development CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name mowund-beta \
            --deployment-group-name MowundBetaDeploymentGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
            
      - if: github.ref == 'refs/heads/stable'
        name: Create Production CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name mowund-beta \
            --deployment-group-name MowundBetaDeploymentGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
