name: Testing
on: [push, pull_request]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable

      - name: Run ESLint
        run: yarn lint
